project_id = "wunrwaoyjgeqpwnhvjxo"

# Supabase Configuration
VITE_SUPABASE_URL=https://wunrwaoyjgeqpwnhvjxo.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bnJ3YW95amdlcXB3bmh2anhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjY2MjIsImV4cCI6MjA2MzA0MjYyMn0.EuA86Q5rm4l4FfTK6qayq9kWm7Kbmc10T3h3K5MxcUA
SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bnJ3YW95amdlcXB3bmh2anhvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzQ2NjYyMiwiZXhwIjoyMDYzMDQyNjIyfQ.kW_Swa0RRnIbTSL64ci_xObN3_FDHp7rvEBqpGEgd_c

# Groq API Configuration
VITE_GROQ_API_KEY=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